# Site settings
title: Muhammad Hassan
email: mohamedtareck95@gmail.com
description: >
  Dedicated Data Analyst and Machine Learning Engineer currently pursuing a Master's in AI and Data Science. Experienced in mathematical modeling, advanced machine learning techniques, software engineering, IoT, and edge computing. Passionate about real-time, efficient data processing in critical environments.

author:
  picture: /assets/img/profile.png
  social:
    twitter: qwtel
    github: muhammadthassan

theme: jekyll-theme-minimal

hydejack:
  dark_mode:
    dynamic: true
    sunrise: 6
    sunset: 18
    icon: true
    always: false
