# Site settings
title: Muhammad Hassan
email: mohamedtareck95@gmail.com
about: |
    Hi, I'm Florian or @qwtel...

    This is another paragraph.
author:
  picture:  /assets/img/profile.png  
  
description: >- # this means to ignore newlines until "baseurl:"
  A showcase of my data science and machine learning projects.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: yourusername
# github_username:  yourgithubusername
author:
  social:
    twitter: qwtel
    github:  qwtel
theme: jekyll-theme-minimal
